---
kind: "operation"
client: "rug-cli 1.0.0-m.1"
generator:
  name: "NewRugProject"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.30.0-20170427011430"
  parameters:
    - "version": "0.1.0"
    - "owner": "atomsit"
    - "description": "Rugs for atomist-community Slack team"

